[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.9"
solana-client = "2.0.3"
solana-program = "2.0.3"
solana-sdk = "2.0.3"

spl-token-2022 = "4.0"
