[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.11"
solana-client = "2.1.7"
solana-program = "2.1.7"
solana-sdk = "2.1.7"

spl-token-2022 = "6.0.0"
